# Generated by Django 5.1.1 on 2024-12-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='image',
            field=models.ImageField(default='', upload_to='Profile', verbose_name='الصورة الشخصية'),
            preserve_default=False,
        ),
    ]
