# Generated by Django 5.1.1 on 2024-12-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profiles_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
    ]
