# Generated by Django 5.1.1 on 2024-12-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profiles_specialist_doctor_profiles_waiting_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='google',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
