# Generated by Django 5.1.1 on 2024-12-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profiles_facebook_profiles_google_profiles_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='join_us',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='وقت الانضمام :'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='google',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
