# Generated by Django 5.1.1 on 2024-12-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profiles_join_us_alter_profiles_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='join',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='وقت الانضمام :'),
        ),
    ]
