# Generated by Django 5.1.1 on 2024-12-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profiles_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='join_us',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='وقت الانضمام :'),
        ),
    ]
