# Generated by Django 5.1.1 on 2024-12-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profiles_join_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='join_us',
        ),
        migrations.AddField(
            model_name='profiles',
            name='type_of_person',
            field=models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=50, null=True, verbose_name='النوع: '),
        ),
    ]
