# Generated by Django 5.1.1 on 2024-12-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_profiles_join_us_profiles_type_of_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='doctor',
            field=models.CharField(blank=True, choices=[('أطفال', 'أطفال'), ('أسنان', 'أسنان'), ('أنف وأذن وحنجرة', 'أنف وأذن وحنجرة'), ('أطفال حديثي الولادة', 'أطفال حديثي الولادة'), ('قلب وأوعية دموية', 'قلب وأوعية دموية'), ('عظام', 'عظام'), ('جلدية', 'جلدية'), ('أمراض نساء وتوليد', 'أمراض نساء وتوليد'), ('أمراض باطنية', 'أمراض باطنية'), ('عيون', 'عيون'), ('مخ وأعصاب', 'مخ وأعصاب'), ('جراحة عامة', 'جراحة عامة'), ('أمراض نفسية', 'أمراض نفسية'), ('أمراض الأطفال', 'أمراض الأطفال'), ('الطب النفسي للأطفال والمراهقين', 'لطب النفسي للأطفال والمراهقين')], max_length=50, null=True, verbose_name='الطبيب'),
        ),
    ]
